version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: TechFix # Você alterou de techfix_db para TechFix, o que é uma mudança válida
    restart: always
    env_file:
      - .env 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init_scripts:/docker-entrypoint-initdb.d # Esta é a parte importante para o script SQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: